language: node_js
node_js:
- 8.1.0
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
- yarn test-ci
- yarn codecov
- yarn snapshot
after_script: greenkeeper-lockfile-upload
deploy:
  provider: heroku
  app: cob-311
  api_key:
    secure: fEjoKeRP0MTvT5V8taQly1Wmfjg5nW3OtkflD+Q1ijzQnFMKOUqvaimBuRFHk+Aqtf08oHhfS8bQlaONVgU7NTa9LcR+GG6UWMMW9PSk0ig4JNpSZhfK/ViLzWN+0jEygG9CL8cojYUY3x5RwdtptdL2kWjTeu1oZ9t3Nw+97yZl64tWbSUkB1RIvizLYhTylaGCcWRfJmfG7bZqxHEsJEgOlxhBnKKIm67Bk8I3CoIesBF5MQ+xK42+yPUwurFr1ZA2o7rxs40GqxeOGikNeGbEcTeDSa9RbAoygoYWyIT2qP+BVTUYInOZ89tX3N7YfWr/f6aivMxejxrY5Wz2BaWypdzPOInY12qIoKRCSqVco0ekFoEPIJF9nBaBlQb8zGhsDeB0ywxnSs1Mxbrc3bcpAarXGyzOctHKVyaUWV1aFv3s0RBADHjk3ph7ZvfoPtKi0TjoR4mMZmhabLiDdTovcq51olERBGLHra2bu9smJhFM+CgJ4yf50LAl9LzFBjvTfcTAwHngWSwUfiUKnotr3liTaGRxqPtvY6nyYyKkxcXA2PyRGh2WDRW9HOXGvdFJS9qSbtLSKqUhsr2krsnemtPcIpcq1RGEZaJlRPlrpezL/utT5teere7vqXQUCG6Kxf7uNpWSS4Y0f+JRKkK2E6DFhKDIe7X5prcPiT4=
  on: master
env:
  secure: Yq411j3wfaEDn+yPeTn1tmgGwhuumvFNZcnP886xUruvXCsVOMpD7VBvDiU+tgkR5xOvgr2ZnmgL0RlCzjAd0xOjRLyeojEe9iBDvjCSjhvgiC4SRLIhNNdEPN7MQ05HoxJf565GyugFGCFr+hbeyhrzuNuK/e2xckFIUMwCkFEXoyyhUVf3A1BaHZvRR5WnXj0oxODRTWQ6tc5NIBcqxGV+Lgc6v5n41RFmeISzq9PeYMJvmlUXp1YDhj5XzgPptZI8Z5Ll4DiI0qAZgRIkY28LQDd0sMH1+3Ctfv7x2OEydOMAMnKPB3OGbq6Kfw02pez+0OgXa7+L5xP5kSqFPaYLcYHv9hBrB8ni8iHmHurh3GmCsm3hyntj1dxLeY3cB4b0h+xNejApqCO0Ts3Ifk9OPLv2SwEJVDbeP+KnP9MDM9crjYbfVVUBiu1eQbghhrZZ1aveayNC5FBfaJC9wipXC8iZoMpUlpZs0z1VWB0AohgFJdbaqGMhNUCi+y6Iu8y04LWpQud1vLlSUoWUt5h6G7B7rskvaWVGqMiT20OP8hFeYLTGi3Ca4dYtKXksd36ssFRKWUHF6oBpx8i4jRDyMcy5JzuJLey9eW3lv/MtqU4GDBFiaLA8Z0dVYrByvIQ1AOstlHAoi5s+JBhZBsNVPNqcrXdJhiJykIKhaQ8=
